//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anketa_Proekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anketa
    {
        public Anketa()
        {
            this.Glasas = new HashSet<Glasa>();
            this.Komentar_Za = new HashSet<Komentar_Za>();
            this.Ogranicuvanjas = new HashSet<Ogranicuvanja>();
            this.Kategorijas = new HashSet<Kategorija>();
            this.Mozni_Odgovori = new HashSet<Mozni_Odgovori>();
        }
    
        public int id_anketa { get; set; }
        public string prasanje { get; set; }
        public string opis_a { get; set; }
        public System.DateTime kraen_datum { get; set; }
        public int id_lice { get; set; }
        public System.DateTime datum_kreiranje { get; set; }
        public int multi_choice { get; set; }
    
        public virtual Louse Louse { get; set; }
        public virtual ICollection<Glasa> Glasas { get; set; }
        public virtual ICollection<Komentar_Za> Komentar_Za { get; set; }
        public virtual ICollection<Ogranicuvanja> Ogranicuvanjas { get; set; }
        public virtual ICollection<Kategorija> Kategorijas { get; set; }
        public virtual ICollection<Mozni_Odgovori> Mozni_Odgovori { get; set; }
    }
}
