//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anketa_Proekt.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AnketiEntities3 : DbContext
    {
        public AnketiEntities3()
            : base("name=AnketiEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anketa> Anketas { get; set; }
        public virtual DbSet<Glasa> Glasas { get; set; }
        public virtual DbSet<Kategorija> Kategorijas { get; set; }
        public virtual DbSet<Komentar> Komentars { get; set; }
        public virtual DbSet<Komentar_Za> Komentar_Za { get; set; }
        public virtual DbSet<Korisnik> Korisniks { get; set; }
        public virtual DbSet<Louse> Lice { get; set; }
        public virtual DbSet<Mozni_Odgovori> Mozni_Odgovori { get; set; }
        public virtual DbSet<Ogranicuvanja> Ogranicuvanjas { get; set; }
        public virtual DbSet<Premium_Korisnik> Premium_Korisnik { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
