//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anketa_Proekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Glasa
    {
        public int id_lice { get; set; }
        public int id_anketa { get; set; }
        public int id_odg { get; set; }
        public Nullable<System.DateTime> datum_glasanje { get; set; }
    
        public virtual Anketa Anketa { get; set; }
        public virtual Louse Louse { get; set; }
        public virtual Mozni_Odgovori Mozni_Odgovori { get; set; }
    }
}
