//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anketa_Proekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Komentar
    {
        public Komentar()
        {
            this.Komentar_Za = new HashSet<Komentar_Za>();
        }
    
        public int id_kom { get; set; }
        public string sodrzina { get; set; }
    
        public virtual ICollection<Komentar_Za> Komentar_Za { get; set; }
    }
}
