//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anketa_Proekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Louse
    {
        public Louse()
        {
            this.Anketas = new HashSet<Anketa>();
            this.Glasas = new HashSet<Glasa>();
            this.Komentar_Za = new HashSet<Komentar_Za>();
            this.Ogranicuvanjas = new HashSet<Ogranicuvanja>();
        }
    
        public int id_lice { get; set; }
        public string ime { get; set; }
        public string prezime { get; set; }
        public string e_mail { get; set; }
        public string lozinka { get; set; }
        public string tel_broj { get; set; }
        public string ulica { get; set; }
        public string grad { get; set; }
        public Nullable<System.DateTime> datum_r { get; set; }
    
        public virtual ICollection<Anketa> Anketas { get; set; }
        public virtual ICollection<Glasa> Glasas { get; set; }
        public virtual ICollection<Komentar_Za> Komentar_Za { get; set; }
        public virtual Korisnik Korisnik { get; set; }
        public virtual Premium_Korisnik Premium_Korisnik { get; set; }
        public virtual ICollection<Ogranicuvanja> Ogranicuvanjas { get; set; }
    }
}
