//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Anketa_Proekt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Premium_Korisnik
    {
        public int id_lice { get; set; }
        public Nullable<System.DateTime> datum_starts { get; set; }
        public Nullable<System.DateTime> datum_end { get; set; }
    
        public virtual Louse Louse { get; set; }
    }
}
